In [1]:
from __future__ import print_function
import json
import os

## Counts by Index: Submission to Annotation Tool

### Team Submissions:

In [8]:
#Uncharted 
unch_hg=json.loads(open('uncharted_hg_pointfact.json').read())
unch_jpl=json.loads(open('uncharted_jpl_pointfact.json').read())
unch_nyu=json.loads(open('uncharted_nyu_pointfact.json').read())

In [9]:
#ISI
isi_nyu=json.loads(open('isi_nyu_pointfact.json').read())
isi_hg=json.loads(open('isi_hg_pointfact.json').read())
isi_jpl=json.loads(open('isi_jpl_pointfact.json').read())

In [10]:
#Georgetown
gt_nyu=json.loads(open('georgetown_nyu_pointfact.json').read())

### Counts of documents:

In [11]:
nyu_counts = len(gt_nyu) + len(unch_nyu) + len(isi_nyu)
nyu_counts

300

In [12]:
hg_counts = len(unch_hg) + len(isi_hg) 
hg_counts

198

In [13]:
jpl_counts = len(isi_jpl) + len(unch_jpl)
jpl_counts

201

```For all PF questions we evaluated against the DD data, 198 submitted documents were from the HG dataset, 201 submitted documents were from the JPL dataset, and 300 submitted documents were from the NYU dataset```